### ISSUE TITLE
Uncompletable Quest: Kurzen's Mystery 

### ISSUE THREAD

**Issue by Mango-Ray** [xgdglb9fpg1j/grizztracker#19] opened 2015-07-25 04:36 UTC
quest=207

Fall of Gurubashi (Object 52) doesn't give the item "The Third Troll Legend" (Item 2007) when looted/interacted with.
"That is already being used" when attempting to loot again.

Quest cannot be completed.

**Comment by xgdglb9fpg1j** [comment] 2015-07-25 14:53
Unable to reproduce/only occurs once already looted and the item is in your bags. Double check and report back, please. Item already being used can be fixed with a relog; core issue, I think.

**Comment by Mango-Ray** [comment] 2015-07-25 21:52
Upon further testing, it seems this occurs when you are at the absolute max range of the object for looting. 

Confirmed, a relog does enable you the chance to loot once more.

**Closed as completed** 2015-07-25 21:53 UTC
